# Generated by Django 3.1.5 on 2021-01-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIBERS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
