# Generated by Django 3.1.5 on 2021-01-25 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('SIBERS', '0002_auto_20210124_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='pic_src_link',
            field=models.CharField(blank=True, max_length=240),
        ),
    ]
